# Query daily for npm dependency updates.
#
version: 2

updates:

  # Enable version updates for github-actions.
  - package-ecosystem: "github-actions"

    # Look for ".github/workflows" in the "root" directory.
    directory: "/"

    # Check for updated GitHub Actions every weekday.
    schedule:
      interval: "daily"

    # Allow up to ten pull requests to be generated at any one time.
    open-pull-requests-limit: 0

#  # Enable version updates for npm.
#  - package-ecosystem: "npm"
#
#    # Look for "package.json" and "package-lock.json" files in the "root" directory.
#    directory: "/"
#
#    # Check the npm registry for updates every weekday.
#    schedule:
#      interval: "daily"
#
#    # Allow up to ten pull requests to be generated at any one time.
#    open-pull-requests-limit: 10
#
#    # Ignore certain dependency updates.
#    ignore:
#      # Ignore node-fetch updates for now due to the breaking change in module management.
#      - dependency-name: "node-fetch"
